word_list=[
    'Christmas',
    'merry',
    'festive',
    'Santa Claus',
    'Saint Nicholas',
    'elves',
    'jolly',
    'reindeer',
    'carols',
    'mistletoe',	
    'frankincense',
    'stocking',
    'presents',
    'candy',
    'Rudolph',
    'sleigh',
    'ornaments',
    'snowball',
    'Christmas tree',
    'sleigh bells',
    'gingerbread house',
    'North Pole',
    'plum pudding'
]